 version=0.1
 [default.global.parameters]
 stack_name = "common-stack"

 [default.deploy.parameters]
 stack_name = "da-black-belt-2021"
 # by default, SAM will create a bucket for your artifacts.
 # Override that here if you have an existing bucket you'd like to use
 # s3_bucket = "adamn-831275422924"
 # comment out 'resolve_s3' line if you use your own bucket
 resolve_s3 = true
 s3_prefix = "analytics-black-belt-2021/sam_deployments/"
 region = "us-east-1"
 confirm_changeset = true
 capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
 tags = "project=\"2021-black-belt\" stage=\"dev\""
 parameter_overrides = """UseCase=rdbms_analytics
    CreateNetworkInfrastructure=TRUE
    CreateDmsVpcRole=TRUE
    CreateDmsInfrastructure=TRUE
    CreateQuickSightInfrastructure=TRUE
    OpsEmailAddress=adam.north@doit-intl.com"""

 [novpc.deploy.parameters]
 stack_name = "novpc"
 # by default, SAM will create a bucket for your artifacts.
 # Override that here if you have an existing bucket you'd like to use
 # s3_bucket = "adamn-831275422924"
 # comment out 'resolve_s3' line if you use your own bucket
 resolve_s3 = true
 s3_prefix = "analytics-black-belt-2021/sam_deployments/"
 region = "us-east-1"
 confirm_changeset = true
 capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
 tags = "project=\"2021-black-belt\" stage=\"dev\""
 parameter_overrides = """
    UseCase=rdbms_analytics_novpc
    CreateNetworkInfrastructure=FALSE
    CreateDmsInfrastructure=TRUE
    CreateQuickSightInfrastructure=TRUE
    VpcSubnetIds=subnet-0c42e559d4f193d7c,subnet-0a19735793dc0ca0e
    OpsEmailAddress=adam.north@doit-intl.com"""
