AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  #TODO

Parameters:
  DbName:
    Type: String
    Default: hammerdb
    AllowedPattern: "[a-z_]+"
    Description: Glue Data Catalog Database Name. Only lower-case and _ allowed.

  ParentStack:
    Type: String
    Description: Parent stack this template was launched from, used for naming SSM parameters

  EmrJobFlowRole:
    Type: String
    Default: "EMR_EC2_DefaultRole"
    Description: EC2 Role for EMR clusters

Resources:
  LakeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      LifecycleConfiguration:
        Rules:
          -
            Id: Expiration
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 2
            NoncurrentVersionExpirationInDays: 7
            ExpiredObjectDeleteMarker: TRUE
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      VersioningConfiguration:
        Status: Enabled

  GlueDatabase:
    Type: AWS::Glue::Database
    DependsOn: LakeBucket
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: Data Lake database
        Name: !Ref DbName
        LocationUri: !Sub 's3://${LakeBucket}/${DbName}/'

  LakeLocationResource:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn: !Join ["/", [ !GetAtt LakeBucket.Arn, !Ref GlueDatabase ]]
      UseServiceLinkedRole: FALSE
      RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/EMR_EC2_DefaultRole'

  EmrLakeDbPermissions:
    Type: AWS::LakeFormation::Permissions
    DependsOn: GlueDatabase
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${EmrJobFlowRole}'
      Permissions:
        - ALL
      Resource:
        DatabaseResource:
          CatalogId: !Ref AWS::AccountId
          Name: !Ref GlueDatabase

  EmrLakeLocationPermissions:
    Type: AWS::LakeFormation::Permissions
    DependsOn: [ GlueDatabase, LakeLocationResource ]
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${EmrJobFlowRole}'
      Permissions:
        - DATA_LOCATION_ACCESS
      Resource:
        DataLocationResource:
          CatalogId: !Ref AWS::AccountId
          S3Resource: !Join ["/", [ !GetAtt LakeBucket.Arn, !Ref GlueDatabase ]]

  EmrLakeTablePermissions:
    Type: AWS::LakeFormation::Permissions
    DependsOn: GlueDatabase
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${EmrJobFlowRole}'
      Permissions:
        - ALL
      Resource:
        TableResource:
          CatalogId: !Ref AWS::AccountId
          DatabaseName: !Ref GlueDatabase
          TableWildcard: {}

  CatalogParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Data lake database name
      Name: !Sub '/${ParentStack}/lake/catalog'
      Type: String
      Value: !Ref GlueDatabase

  BucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Data Lake s3 bucket
      Name: !Sub '/${ParentStack}/lake/bucket'
      Type: String
      Value: !Ref LakeBucket

  PrefixParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Data Lake s3 prefix uri
      Name: !Sub '/${ParentStack}/lake/prefix_uri'
      Type: String
      Value: !Join ['', ['s3://', !Ref LakeBucket, '/', !Ref GlueDatabase]]
