AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Stack which contains the Data Lake related resources (Glue, S3, Lake Formation etc)

Parameters:
  UseCase:
    Type: String
    Default: hammerdb
    AllowedPattern: "[a-z_]+"

  ParentStack:
    Type: String
    Description: Parent stack this template was launched from, used for naming SSM parameters

Resources:
  LakeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      LifecycleConfiguration:
        Rules:
          -
            Id: Expiration
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 2
            NoncurrentVersionExpirationInDays: 7
            ExpiredObjectDeleteMarker: TRUE
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      VersioningConfiguration:
        Status: Enabled

  GlueDatabase:
    Type: AWS::Glue::Database
    DependsOn: LakeBucket
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: Data Lake database
        Name: !Ref UseCase
        LocationUri: !Sub 's3://${LakeBucket}/${UseCase}/'

  LakeFormationLocationRole:
    Type: AWS::IAM::Role
    DependsOn: [ LakeBucket, GlueDatabase ]
    Properties:
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": [ "lakeformation.amazonaws.com" ]
            },
            "Action": [ "sts:AssumeRole" ]
          }
        ]
      }
      Description: Service role for LakeFormation
      MaxSessionDuration: 43200
      Policies:
        - PolicyName: LakeFormation
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: ListAll
                Effect: Allow
                Action:
                  - s3:ListAllMybuckets
                Resource: !Sub 'arn:${AWS::Partition}:s3:::*'
              - Sid: ListBucket
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt LakeBucket.Arn
              - Sid: S3ObjectAccess
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource:
                  - !Join ["/", [ !GetAtt LakeBucket.Arn, !Ref GlueDatabase, '*' ] ]
                  - !Join ["/", [ !GetAtt LakeBucket.Arn, !Ref GlueDatabase ] ]

  LakeLocationResource:
    Type: AWS::LakeFormation::Resource
    DependsOn: LakeFormationLocationRole
    Properties:
      ResourceArn: !Join ["/", [ !GetAtt LakeBucket.Arn, !Ref GlueDatabase ]]
      # ServiceLinkedRole does not properly delete using CloudFormation so using a traditional IAM role
      UseServiceLinkedRole: FALSE
      RoleArn: !GetAtt LakeFormationLocationRole.Arn

  CatalogParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Data lake database name
      Name: !Sub '/${ParentStack}/lake/catalog'
      Type: String
      Value: !Ref GlueDatabase

  BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Data Lake s3 bucket
      Name: !Sub '/${ParentStack}/lake/bucket/name'
      Type: String
      Value: !Ref LakeBucket

  BucketArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Data Lake s3 bucket
      Name: !Sub '/${ParentStack}/lake/bucket/arn'
      Type: String
      Value: !GetAtt LakeBucket.Arn

  PrefixParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Data Lake s3 prefix uri
      Name: !Sub '/${ParentStack}/lake/prefix_uri'
      Type: String
      Value: !Join ['', ['s3://', !Ref LakeBucket, '/', !Ref GlueDatabase]]

  LakeFormationLocationRoleParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: LakeFormation IAM role
      Name: !Sub '/${ParentStack}/lake/iam/lf/role_id'
      Type: String
      Value: !GetAtt LakeFormationLocationRole.RoleId



