AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Infrastructure components required at runtime for the pipeline resources to function

Parameters:
  ParentStack:
    Type: String
    Description: Parent stack this template was launched from, used for naming SSM parameters

  CreateDmsVpcRole:
    Type: String
    Description: Whether or not to create the DMS VPC Role
    AllowedValues: [ 'TRUE', 'FALSE' ]
    Default: 'FALSE'

Conditions:
  CreateDmsVpcRole: !Equals [ !Ref CreateDmsVpcRole, 'TRUE' ]

Resources:
  SourceConfigTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: identifier
          AttributeType: S
        - AttributeName: config
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: identifier
          KeyType: HASH
        - AttributeName: config
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: TRUE

  RuntimeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      LifecycleConfiguration:
        Rules:
          -
            Id: Expiration
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 2
            NoncurrentVersionExpirationInDays: 7
            ExpiredObjectDeleteMarker: TRUE
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      VersioningConfiguration:
        Status: Enabled

  #  If DMS has not been previously used in this account, you will need to create the dms-vpc-role or DMS resources in this stack will fail
  #  With error: The IAM Role arn:aws:iam::831275422924:role/dms-vpc-role is not configured properly.
  #  This can be done through the GUI by manually configuring a Subnet group, or
  #  by Parameter CreateDmsVpcRole=TRUE in template runtime-infrastructure.yaml. If the role already exists, just set this to FALSE
  DmsVpcRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Condition: CreateDmsVpcRole
    Properties:
      RoleName: dms-vpc-role
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": [ "dms.amazonaws.com" ]
            },
            "Action": [ "sts:AssumeRole" ]
          }
        ]
      }
      Description: VPC Service role for DMS
      ManagedPolicyArns:
        - !Sub 'arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole'

  SourceConfigTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: DynamoDB table for data source configs
      Name: !Sub '/${ParentStack}/runtime/config_table/name'
      Type: String
      Value: !Ref SourceConfigTable

  SourceConfigTableArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: DynamoDB table for data source configs
      Name: !Sub '/${ParentStack}/runtime/config_table/arn'
      Type: String
      Value: !GetAtt SourceConfigTable.Arn

  RuntimeBucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Runtime s3 bucket name
      Name: !Sub '/${ParentStack}/runtime/bucket/name'
      Type: String
      Value: !Ref RuntimeBucket

  RuntimeBucketArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Runtime s3 bucket arn
      Name: !Sub '/${ParentStack}/runtime/bucket/arn'
      Type: String
      Value: !GetAtt RuntimeBucket.Arn
