AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Create an empty secret to be referenced by the pipeline. Secret values should be entered manually after creation.

Parameters:
  ParentStack:
    Type: String
    Description: Parent stack this template was launched from, used for naming SSM parameters

  SecretName:
    Type: String
    Default: hammerdb
    AllowedPattern: "[a-z_]+"
    Description: Suffix of the SecretsManager secret

Resources:
  # This is just an example secret to demonstrate the format of a database secret
  # Actual secret values should be entered into secretsmananager manually after it is created
  RdbmsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Example secret
      Name: !Sub '${ParentStack}/rdbms/${SecretName}'
      SecretString:  >
        {
          "username": "",
          "password": "",
          "engine": "postgres",
          "host": "",
          "port": "",
          "dbname": ""
        }

  RdbmsSecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Rdbms example secret
      Name: !Sub '/${ParentStack}/secrets/${SecretName}'
      Type: String
      Value: !Ref RdbmsSecret
