AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  #TODO

Parameters:
  ParentStack:
    Type: String
    Description: Parent stack this template was launched from, used for naming SSM parameters

Resources:
  FullLoadRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": [ "states.amazonaws.com" ]
            },
            "Action": [ "sts:AssumeRole"]
          }
        ]
      }
      Description: Role for full load state machine
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEMRFullAccessPolicy_v2
      MaxSessionDuration: 43200

  FullLoadStepFunction:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ../src/stepfunctions/full_load.json
#      #DefinitionSubstitutions:
#        # /da-black-belt-2021/lake/prefix
#        LakeUri: !Join ['',
#          [
#            '{{resolve:ssm:/',
#            !Ref ParentStack,
#            '/lake/prefix',
#            '}}',
#          ]
#        ]
      Role: !GetAtt FullLoadRole.Arn
      Type: STANDARD

  FullLoadStepFunctionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Step function arn
      Name: !Sub '/${ParentStack}/stepfunctions/full_load_arn'
      Type: String
      Value: !Ref FullLoadStepFunction
